/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package suche2024;

/**
 *
 * @author mag
 */
public class SucheGUI extends javax.swing.JFrame {

    /**
     * Creates new form SucheGUI
     */
    public SucheGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        sucheLandButton = new javax.swing.JButton();
        sucheLandMinButton = new javax.swing.JButton();
        sucheLandMinIndexButton = new javax.swing.JButton();
        sucheLandIndexButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ausgabeArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Suchen"));

        jLabel1.setText("Ländername:");

        sucheLandButton.setText("Suche Land");
        sucheLandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheLandButtonActionPerformed(evt);
            }
        });

        sucheLandMinButton.setText("Suche Land mit kleinster Fläche");
        sucheLandMinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheLandMinButtonActionPerformed(evt);
            }
        });

        sucheLandMinIndexButton.setText("Suche Index von Land mit kleinster Fläche");
        sucheLandMinIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheLandMinIndexButtonActionPerformed(evt);
            }
        });

        sucheLandIndexButton.setText("Suche Index von Land");
        sucheLandIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheLandIndexButtonActionPerformed(evt);
            }
        });

        ausgabeArea.setColumns(20);
        ausgabeArea.setRows(5);
        jScrollPane1.setViewportView(ausgabeArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sucheLandButton)
                    .addComponent(sucheLandMinButton)
                    .addComponent(sucheLandMinIndexButton)
                    .addComponent(sucheLandIndexButton))
                .addGap(0, 139, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sucheLandButton, sucheLandIndexButton, sucheLandMinButton, sucheLandMinIndexButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sucheLandButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sucheLandIndexButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sucheLandMinButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sucheLandMinIndexButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sucheLandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheLandButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheLandButtonActionPerformed

    private void sucheLandIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheLandIndexButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheLandIndexButtonActionPerformed

    private void sucheLandMinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheLandMinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheLandMinButtonActionPerformed

    private void sucheLandMinIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheLandMinIndexButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheLandMinIndexButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SucheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SucheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SucheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SucheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucheGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ausgabeArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton sucheLandButton;
    private javax.swing.JButton sucheLandIndexButton;
    private javax.swing.JButton sucheLandMinButton;
    private javax.swing.JButton sucheLandMinIndexButton;
    // End of variables declaration//GEN-END:variables
}
